IF
	Global("VP_Sime_Aran","GLOBAL",1)
	NumTimesTalkedTo(0)
	See("Sime")
THEN
	RESPONSE #100
		Dialogue("Sime")
END

IF
	Global("VP_Sime_Aran","GLOBAL",1)
	NumTimesTalkedTo(0)
	!See("Sime")
THEN
	RESPONSE #100
		MoveToObject("Sime")
		StartDialogueNoSet("Sime")
END

IF
	Global("VP_AranLeaves","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("VP_AranLeaves","GLOBAL",2)
		ReallyForceSpell(Myself,DRYAD_TELEPORT)
END


