IF
	Global("StartEndBios","AR6200",1)
	InParty("Sarevok")
	Global("SarevokBio","GLOBAL",0)
	!Global("VP_Kr_Epilogue","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("SarevokBio","GLOBAL",1)
		TextScreen("SAREVND")
		SmallWait(1)
		Continue()
END

IF
	Global("StartEndBios","AR6200",1)
	InParty("Sarevok")
	Global("SarevokBio","GLOBAL",0)
	Global("VP_Kr_Epilogue","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("SarevokBio","GLOBAL",1)
		TextScreen("SAREVND1")
		SmallWait(1)
		Continue()
END