CHAIN BAERIE25 TS166
~I thought... or never mind... You will laugh...~
EXTERN BVALYG25 TS190

CHAIN BAERIE25 TS167
~But you... you will laugh at me...~
EXTERN BVALYG25 TS191

CHAIN BAERIE25 TS168
~I thought that you... you might be Shaundakul's avatar... You are tall and handsome and dark-haired... You are dressed in the plain leather and you step lightly.~
EXTERN BVALYG25 TS192

CHAIN BAERIE25 TS169
~I knew... I knew you would laugh.~
EXTERN BVALYG25 TS193

CHAIN BAERIE25 TS170
~Valygar, do you ever think about anybody but <CHARNAME>?~
EXTERN BVALYG25 TS194

CHAIN BAERIE25 TS171
~No... nothing... Do not mind me...~
EXTERN BVALYG25 TS195