CHAIN BANOMEN TS587
~Ahem, Yoshimo, I had... accidentally... noticed that you are writing something. Well, poetry. So you have poetry in Kara-Tur?~
EXTERN BYOSHIM TS100

CHAIN BANOMEN TS588
~That's a good start... was it what you were writing for the past fortnight? Keep up good work, Yoshimo and you might actually finish it.~
EXTERN BYOSHIM TS101

CHAIN BANOMEN TS589
~Oh, you are working for dwarven market? New style? Short poetry for short people?~
EXTERN VPKACB 16

CHAIN BANOMEN TS590
~Kachiko, the poetry is a dove which whispers tender desires to the Lady of the heart... Not a childish line and a half... If I may offer you a real madrigal:

She walks in beauty, like the night
Of cloudless climes and starry skies;
And all that's best of dark and bright
Meet in her aspect and her eyes:
Thus mellow'd to that tender light
Which heaven to gaudy day denies...~
EXTERN VPKACB 17

CHAIN BANOMEN TS591
~The judge is not objective! My star, come, tell what you think?~
END
 ++ ~What, the poem you wrote about Kachiko? Well, I'd say I agree with her, it's not the greatest...~ EXTERN BANOMEN TS592

CHAIN BANOMEN TS592
~All that nights I spend writing it for you... all wasted...~
END
 ++ ~On the second thought, may we call it a tie, Kachiko?~ EXTERN VPKACB 18

CHAIN BANOMEN TS593
~A tie? A TIE?~
EXTERN BYOSHIM TS103

CHAIN BANOMEN TS594
~Valygar, if she needed anybody's help she'd ask for it.~
EXTERN BVALYGA TS174

CHAIN BANOMEN TS595
~Verily, Valygar, I know little of love beside what the tales say. I would speak to an older comrade in the Order, but I thought you might be willing to listen. Besides, the girl I like, well, she is very special... It's <CHARNAME> and with her heritage, I am not sure the Order would look benevolently on our relationship...~
EXTERN BVALYGA TS379

CHAIN BANOMEN TS596
~See my problem? Of all fair ladies I love the one who would never be accepted by the Order as my bride...~
EXTERN BVALYGA TS380

CHAIN BANOMEN TS597
~Why are you so upset Valygar? I merely...~
EXTERN BVALYGA TS382

CHAIN BANOMEN TS598
~Have you never met a nice girl?~
EXTERN BVALYGA TS383

CHAIN BANOMEN TS599
~I think I am luckier than you then. <CHARNAME> is a woman of rare virtue...~
EXTERN BVALYGA TS384

CHAIN BANOMEN TS600
~You should try. She went mad, dragging us all over the place instead of saving the elven city. Many lives were forsaken to save yours. Verily, a worthy exchange! It would seem that you have some special value in the eyes of <CHARNAME>.~
EXTERN BVALYGA TS386

CHAIN BANOMEN TS601
~Is that true <CHARNAME>? Would you do it, say, for me?~
END
 ++ ~Yes I would. Now cool down, you are acting irrationally.~ EXTERN BANOMEN TS602
 ++ ~I am not going to answer that. Think what you will, Anomen, I just do not care.~ EXTERN BVALYGA TS389
 ++ ~No. I would have left you to rot in the crypt. ~ EXTERN BANOMEN TS604

CHAIN BANOMEN TS602
~I... I was... I am sorry my Lady.~
END
 ++ ~You should apologize to Valygar, not to me...~ EXTERN BANOMEN TS603
 ++ ~Apology accepted. Now, let's all calm down and do our job.~ EXTERN BVALYGA TS388

CHAIN BANOMEN TS603
~Oh, that? Well, Valygar, I must say I had been ill-tempered and said what I should have not...~
EXTERN BVALYGA TS387

CHAIN BANOMEN TS604
~Oh, I see... Well, then I'll relieve you from the necessity of being in my company. Fare thee well.~
DO ~LeaveParty() EscapeArea()~
EXIT

CHAIN BANOMEN TS605
~Somehow I do not think so. She cares not if I would turn into a stone or a turnip... or a vampire.~
EXTERN BVALYGA TS390

CHAIN BANOMEN TS606
~Indeed, it would serve me well. Looks like <CHARNAME> is into the strong and silent type.~
EXIT

CHAIN BANOMEN TS607
~I have a strange suspicion, ranger. I think you are trying to...~
EXTERN BVALYGA TS462

CHAIN BANOMEN TS608
~You know what!~
EXTERN BVALYGA TS463

CHAIN BANOMEN TS609
~Laughing! Sure, you can laugh! It's my heart that is bleeding!~
EXTERN BVALYGA TS464

CHAIN BANOMEN TS610
~I want NOTHING from you!~
EXTERN BVALYGA TS465

CHAIN BANOMEN TS611
~I am not through with you yet! You cannot just walk away!~
EXTERN BVALYGA TS466

CHAIN BANOMEN TS612
~I have seen you together... Do not try to deny it! You hold her hand! You who have told me endlessly how uninterested you are in ladies! I was so blind. I let you to steal <CHARNAME> from me...~
EXTERN BVALYGA TS468

CHAIN BANOMEN TS613
~Spend time indeed... Travel to Zakhara - that's going to give you two a lot of time to kill.~
EXTERN BVALYGA TS469

CHAIN BANOMEN TS614
~I should have done that long ago, instead of trusting her, instead of trusting you. It is my own fault that the one I love and you, whom I called my friend, have broken my life. I was too carefree. Now they all look at me with pity and say nice words. But my heart is the vulture's food. Nothing hurts more than treachery.~
EXTERN BVALYGA TS470

CHAIN BANOMEN TS615
~How dare you!~
EXTERN BVALYGA TS471

CHAIN BANOMEN TS616
~Oh, now it's my own fault, is not it?~
EXTERN BVALYGA TS472

CHAIN BANOMEN TS617
~I see... May be she would have more to say?~
EXTERN BVALYGA TS473

CHAIN BANOMEN TS618
~Are you threatening me?~
EXTERN BVALYGA TS474

CHAIN BANOMEN TS619
~I care not what you told me. My conversation with her is a private one.~
EXTERN BVALYGA TS551

CHAIN BANOMEN TS620
~Jealous? Of course you are jealous! She loves me, not you!~
EXTERN BVALYGA TS552

CHAIN BANOMEN TS621
~What! I love her more than my own life, and I will hurt her? You are going queer, ranger! I just need to talk to her. <CHARNAME>, I beg you to tell me what is going on... Do you like Valygar better than I?~
END
 ++ ~That's enough. Valygar, you have some sort of idea-fix that everyone tries to hurt me and you are the one to save me. Let me remind you, that I am quite capable of taking care of myself. Besides I do not desire to be protected from the love of my life, Anomen... (*give Anomen a sweet smile*)~ EXTERN BVALYGA TS553
 ++ ~I think I know the way to solve this conflict: I care for neither of you. But I consider both of you my friends. So do make up and let's forget about this silly conversation.~ EXTERN BVALYGA TS554
 ++ ~Ahem... Anomen. I do not know how you came up with the notion that I like you... I am sorry if I have given you a false hope. I prefer you not to intervene into my relationship with Valygar. ~ EXTERN BVALYGA TS556
 ++ ~(*grin... and stay silent waiting for the next scene*)~ EXTERN BVALYGA TS558
 ++ ~(*cry helplessly*) Fools, I... I love both of you. Please, do not make me choose...~ EXTERN BVALYGA TS560

CHAIN BANOMEN TS622
~I cannot believe my own ears!~
EXTERN BVALYGA TS555

CHAIN BANOMEN TS623
~I do not want to hear another word! I have to be alone now.~
DO ~ChangeAlignment(Myself,CHAOTIC_NEUTRAL)~
EXIT

CHAIN BANOMEN TS624
~I do not want to hear another word! I have to be alone now.~
DO ~LeaveParty() EscapeArea()~
EXIT

CHAIN BANOMEN TS625
~Let me go talk to her! Or I swear I will kill you!~
EXTERN BVALYGA TS559

CHAIN BANOMEN TS626
~How dare you are...~
DO ~SetGlobal("AnomenValygarFight","GLOBAL",1) SetLeavePartyDialogueFile() LeaveParty() ChangeAIScript("",DEFAULT) ChangeAIScript("useitem",GENERAL) ChangeAIScript("anvsval",SPECIFICS)~
EXIT

CHAIN BANOMEN TS627
~Nay my Lady, not in the least.~
EXTERN VPSIMB 40

CHAIN BANOMEN TS628
~You should my Lady, you should.~
EXTERN VPSIMB 41

CHAIN BANOMEN TS629
~It is most hurtful to hear such harsh words from a noble born Lady.~
EXTERN VPSIMB 42

CHAIN BANOMEN TS630
~But surely, your Lady mother was of a high station...~
EXTERN VPSIMB 43

CHAIN BANOMEN TS631
~Mayhaps you are a Princess of some enchanted place and you know not of it, my Lady?~
EXTERN VPSIMB 44

CHAIN BANOMEN TS632
~My Lady, you are an observant friend. I am worried of my feeling about our company.~
EXTERN VPSIMB 46

CHAIN BANOMEN TS633
~Quite the opposite, my dear Sime, quite the opposite...~
EXTERN VPSIMB 47

CHAIN BANOMEN TS634
~Our group is lacking discipline and the purpose. Yet I like it. What would the Prelate of the Order say if he would learn that I am not insistent enough on proper procedures? When are we to undertake the heroic deeds fit for a paladin of the Order?~
EXTERN VPSIMB 48

CHAIN BANOMEN TS635
~Aye, you speak truthfully, my Lady. And that was "the pool of right"... I suppose I strike evil in the name of the Order and I am pleased with it. Menial tasks or no, we do good things. But the lack of discipline and insubordination does not sit well with me!~
EXTERN VPSIMB 49