CHAIN BCERND TS100
~What's your heart telling you on that account, ranger?~
EXTERN VPSIMB 167

CHAIN BCERND TS101
~You sound very sure. Why ask me then, Sime?~
EXTERN VPSIMB 168

CHAIN BCERND TS102
~I know that every living thing has dreams, Sime. The Oak Father granted me a rare spell once and I... I was fortunate enough to see the dreams of a beast then.~
EXTERN VPSIMB 169

CHAIN BCERND TS103
~A spotted lion. A strange and wonderful thing are the beast's dreams, Sime. Wild and so... unrestricted.~
EXTERN VPSIMB 170

CHAIN BCERND TS104
~(*shakes his head*) No, Sime. They cannot be put in words, those images. Pray to have an experience like that for yourself.~
EXTERN VPSIMB 171

CHAIN BCERND TS105
~Yes. They are expecting me back at the Grove.~
EXTERN VPSIMB 173

CHAIN BCERND TS106
~All things happen in due course in nature. My part now is to follow Bhaal's child.~
EXTERN VPSIMB 174

CHAIN BCERND TS107
~Demigods are strange creatures, Sime. I know that Bhaal's blood torments <CHARNAME>. If I am not mistaken, events mysterious and terrible are brewing... The fate of the greater balance depends on how well <CHARNAME> can maintain the balance of <PRO_HISHER> soul. Someone who understands the ways of Balance needs to be watching after <PRO_HIMHER>.~
EXTERN VPSIMB 175

CHAIN BCERND TS108
~I would, Sime. I yearn to return to the Grove and be with him. But the very fate of my child depends on the actions of <CHARNAME>. Balance must be preserved...~
EXTERN VPSIMB 176