CHAIN BEDWIN TS106
~I do not expect a group of unruly imbeciles to even start to understand my grandeur and finesse. I wish no stupid statements like that in the future from you, wench.~
EXTERN VPKACB 56

CHAIN BEDWIN TS107
~Or I'll destroy you, or yours precious samurai, or both of you (*yawns*).~
EXTERN BYOSHIM TS107

CHAIN BEDWIN TS108
~Fortunately to me, and unfortunately to you, we won't meet again (*finally, I get rid of these fools*).~
DO ~LeaveParty() EscapeArea()~
EXIT

CHAIN BEDWIN TS109
~You will suffer yet...~
DO ~LeaveParty() Enemy()~
EXIT

CHAIN BEDWIN TS110
~Yes, pretty face, I had noticed you and that should put a smile on any maiden's face. (This one is smarter than she looks. She appreciates me and shows appropriate reverence.)~
EXTERN VPSIMB 139

CHAIN BEDWIN TS111
~I am coming to the conclusion that mutual attraction is growing between the most attractive and intelligent person in this pathetic troupe and his devoted maid. (Should I have included some compliment for the wench? No, that would be giving her too much. She is gasping in anticipation already.)~
EXTERN VPSIMB 140

CHAIN BEDWIN TS112
~Sime, you had better sit down, least your happiness takes you off your feet. (Amazing imbecile. Comes of roaming the wilds in the company of beasts, no doubt. I should be more direct with the likes of her. But she can be educated, I hope.)~
EXTERN VPSIMB 141

CHAIN BEDWIN TS113
~Sime, I had devised that you, poor soul, are deeply taken by my superior charms. While it is clear that you are inferior to me I am willing to condescend and bring the relationship to consummation tonight.~
EXTERN VPSIMB 142

CHAIN BEDWIN TS114
~Fool woman, my look and style are perfect. How dare you to suggest an imbalance? (And I thought she had a grain of sense!)~
EXTERN VPSIMB 144

CHAIN BEDWIN TS115
~You do not suggest seriously that I might have pay attention to anything tree-hugging rabble have to say?~
EXTERN VPSIMB 145

CHAIN BEDWIN TS116
~I do not see how it is relevant to the kiss you were ordered to give me, but indeed I have an intelligent concept of the world's balance (do I even dare to hope that someone can understand a scheme so perfectly devised?)~
EXTERN VPSIMB 146

CHAIN BEDWIN TS117
~I can see that you are not as hopelessly foolish as I originally thought (I would have to use my charm, the wench is stubborn) but you should not be afraid of my greatness. I am a red-blooded male as well as an intellectual pinnacle of mankind.~
EXTERN VPSIMB 147

CHAIN BEDWIN TS118
~Elves? An outdated and almost extinct nation. The only true power lies with humans.~
EXTERN VPSIMB 148

CHAIN BEDWIN TS119
~You had the most annoying outburst of base emotions when I have spoken to you last time. (Must I explain everything to those imbeciles?) I am interested to know if you saw the truth of my words and are ready to apologize for your unspeakable behavior?~
EXTERN VPSIMB 150

CHAIN BEDWIN TS120
~I fail to understand how you can fight off your attraction to me for so long. It must be very painful to be away from my gorgeous body and not to be a receptacle of my nearly divine wisdom.~
EXTERN VPSIMB 151

CHAIN BEDWIN TS121
~I have suspected that you with your narrow mind were interested in some stupid joke. (I have a long memory and I shall have revenge.)~
EXTERN VPSIMB 152

CHAIN BEDWIN TS122
~(Is it not amazing how their attitude can change.) I am coming, wench.~
EXTERN VPSIMB 154

CHAIN BEDWIN TS123
~Here I am, in all my glorious beauty... What is it? Why are you dressed? And armored? And you hold your mace? Sime, my love...~
EXTERN VPSIMB 155

CHAIN BEDWIN TS124
~Only for the love of you my queen, my dear elven queen... You would not hurt your humble slave, will you? I am naked and defenseless before you... (*tries to cast a fireball*)~
EXTERN VPSIMB 156

CHAIN BEDWIN TS125
~But my sweet charming elven beauty... (How many more humiliation the wench wants me to go through?)~
EXTERN VPSIMB 157

CHAIN BEDWIN TS126
~I... shall... leave Sime alone!~
EXTERN VPSIMB 158