CHAIN BIMOEN25 TS112
~Marriage? Wow, Valygar are you finally making the move? Common, <CHARNAME>, don't just stand there gaping at me! You are not that elderly yet, my big sis...~
EXTERN BVALYG25 TS103

CHAIN BIMOEN25 TS113
~Abstract? You can't be abstract about a wedding! Baldur's Gate is the best place I figure, though since you are from Athkatla, may be <CHARNAME> will settle for it. But only the biggest temple will do...~
EXTERN BVALYG25 TS104

CHAIN BIMOEN25 TS114
~Talos? No! Wouldn't it be appropriate if Bhaal's temples were still open for business, but before we find one, we'd lose too much time and it will be difficult to gather all 500 guests in some dank hole were Bhaalists linger nowadays? Lathander might do.~
END
 ++ ~Imoen, I am afraid you did not get the point: nobody is getting married.~ EXTERN BIMOEN25 TS115

CHAIN BIMOEN25 TS115
~Well, if you plan to be an old maid it's your choice. But it could have been so beautiful: a warm day in the summer, flowers everywhere, tons of guests... You would be dressed in a huge white dress... Of course I'd be your maid of honor... I have seen an absolutely gorgeous pink silk! It will suit my hair perfectly and I'd look like million gold pieces... I'd look like a veritable goddess in that dress...~
END
 ++ ~And of cause the eyes of all the cute men in the room centered on you...~ EXTERN BIMOEN25 TS116

CHAIN BIMOEN25 TS116
~Yes! Huge crowd, songs, people going delirious with happiness... How sweet and sad... Why you are so stubborn?~
EXTERN BVALYG25 TS105

CHAIN BIMOEN25 TS117
~I dunno, Valygar. Granted, our mothers had lousy taste in man, that's for sure! But Bhaal's not the only jerk to have had kids who have become good people. I've seen decent folk among the Bhaalspawn in Saradush. We all turned out differently. And with the amount of children Bhaal sired some were bound to be evil or insane...~
EXTERN BIMOEN25 TS118

CHAIN BIMOEN25 TS118
~<CHARNAME> is moody sometimes and Bhaal's blood is stronger in her than in me or most of the others... yet she is not a murderous berserker. I am very happy to have <CHARNAME> as my sister. I enjoy our friendship and loyalty that shared blood can bring.~
EXTERN BVALYG25 TS107

CHAIN BIMOEN25 TS119
~Maybe you grow weary of the company of Bhaalspawn and their duties and their endless struggles? Do you want to return back to your solitude in the Umar Hills?~
EXTERN BVALYG25 TS108

CHAIN BIMOEN25 TS120
~Why?~
EXTERN BVALYG25 TS109

CHAIN BIMOEN25 TS121
~No other reason?~
EXTERN BVALYG25 TS110