CHAIN BIMOEN2 0
~(Shudders) Yes, Kachiko it was an awful place, run by an insane madman... I thought that I would never be able to sleep peacefully again...~
EXTERN VPKACB 59

CHAIN BIMOEN2 1
~My wounds are deep and my pain is not passing. I just cannot be my old self again. But I am grateful for your kind words. We... we should catch up with the rest of the group, Kachiko.~
EXTERN VPKACB 60

CHAIN BIMOEN2 2
~And both are absolutely gorgeous goddesses! And, Valygar, you are leaving out the most interesting part. Which one of us you like the better?~
EXTERN BVALYGA TS326

CHAIN BIMOEN2 3
~(Laughs) You do not have to answer. But I am not just gorgeous I am also generous. I will tell you something you will probably be interested in hearing. The lights were bad in Spellhold, but I think I spotted <CHARNAME> blush when she mumbled: "Valygar, the ranger, my new trusted friend..."~
EXTERN BVALYGA TS327

CHAIN BIMOEN2 4
~Nope, I just made it up. I wanted to check my theory. I think you got a thing for her...~
EXTERN BVALYGA TS328

CHAIN BIMOEN2 5
~Oh, really? How exciting, I know something, which has not happened yet...~
EXIT

CHAIN BIMOEN2 6
~Nope, Sime. I'm fine at last. Just tryin' to shake off the nightmares. I was just thinkin' on how many new faces are around. Yours for instance.~
EXTERN VPSIMB 110

CHAIN BIMOEN2 7
~Must have been complaining about <PRO_HISHER> "little troublemaker" as usual. <CHARNAME> never noticed that I grew up, I am afraid.~
EXTERN VPSIMB 111

CHAIN BIMOEN2 8
~Jaheira says I look silly when I smile. Well, actually her exact words were "sillier than usual".~
EXTERN VPSIMB 112

CHAIN BIMOEN2 9
~(Pssst) I do not steal, Sime, I just look. Don't ya wanna know what each of them might be carrying around in secret?~
EXTERN VPSIMB 114

CHAIN BIMOEN2 10
~Aerie carries a mirror and... blush!~
EXTERN VPSIMB 115

CHAIN BIMOEN2 11
~Korgan carries a a book entitled "How to Make Friends and Influence Other People".~
EXTERN VPSIMB 116

CHAIN BIMOEN2 12
~Guess what our somber ranger carries? A laced lady's glove!~
EXTERN VPSIMB 117

CHAIN BIMOEN2 13
~Nope!~
EXTERN VPSIMB 118

CHAIN BIMOEN2 14
~Oh, my dear Mystra, just look at that! Anomen has...~
EXTERN VPSIMB 119

CHAIN BIMOEN2 15
~Cernd has some sort of seeds here. And bark. And pebbles.~
EXTERN VPSIMB 120

CHAIN BIMOEN2 16
~Jan has a turnip, no two turnips... three... ten...~
EXTERN VPSIMB 121

CHAIN BIMOEN2 17
~Yoshimo has nothing, but his weapons and this other stuff he is carrying for <CHARNAME>.~
EXTERN VPSIMB 122

CHAIN BIMOEN2 18
~Kachiko has a lock of dark hair!~
EXTERN VPSIMB 123

CHAIN BIMOEN2 19
~Nalia has some sort of blueprints. Looks like it is her castle.~
EXTERN VPSIMB 124

CHAIN BIMOEN2 20
~Keldorn has a pipe and smoking weed. But I have never seen him smoking!~
EXTERN VPSIMB 125

CHAIN BIMOEN2 21
~Mazzy has high-heeled shoes!~
EXTERN VPSIMB 126

CHAIN BIMOEN2 22
~Jaheira has a portrait of Khalid.~
EXTERN VPSIMB 127

CHAIN BIMOEN2 23
~Well, he carries Boo, cheese for Boo, peanuts for Boo and carrots for Boo...~
EXTERN VPSIMB 128

CHAIN BIMOEN2 24
~"How I Became an Evil Overlord" by Edwin Odesseiron.~
EXTERN VPSIMB 129

CHAIN BIMOEN2 25
~I am afraid to pick-pocket Viconia. If she wakes up, she'll kill me on spot.~
EXTERN VPSIMB 130

CHAIN BIMOEN2 8A
~<CHARNAME> says I look silly when I smile. Well, actually <PRO_HISHER> exact words were "sillier than usual".~
EXTERN VPSIMB 112A