CHAIN BJAN TS116
~I must not forget any detail of what happened on the Island. I have come up with the most potentially profitable business. We are going to make a tourist attraction out of your story, Kachiko. Charge to enter in the crypt, see you there dead... Then Yoshimo comes and gives you that big romantic kiss and you come back to life. And then the families run in bashing each other on the head and crying for the death of both of you. My cousin Willy he'd write good play about that and...~
EXTERN VPKACB 68

CHAIN BJAN TS117
~You do not need the Island, girl! That the whole point! We are going to dig some cave near Athkatla and say that it all happened there...~
EXTERN VPKACB 69

CHAIN BJAN TS118
~None of course! But we do not need Kara-Turians. Locals like local stories. We'd give you some pretty names like Julia and Romano and your families would be say rival clans... Or may be Harpers and Shadow Thieves? Cousin Willy, he is good at that. Speaking of about cousin Willy, have I ever told you how he wrote his first play? Actually it's funny, because he did not write it... Did I tell you about that?~
EXTERN VPKACB 70

CHAIN BJAN TS119
~I do not recall...~
EXTERN VPKACB 71

CHAIN BJAN TS120
~I think I have some ointment for that scar you've got. Made from distilled turnips and orc urine - works a treat. Jansen's honour! We'd have you looking lovely in no time at all.~
EXTERN BVALYGA TS492

CHAIN BJAN TS121
~What scar? Why the one on your face oozing that brown mucus. Did I ever tell you the story about cousin Gustav and his incredible mucus-hurling machine? It could throw a ten-pound lump almost...~
EXTERN BVALYGA TS493

CHAIN BJAN TS122
~Oh mud, of course! Well the offer of the ointment is still open in case you should develop a real scar...~
EXTERN BVALYGA TS494

CHAIN BJAN TS123
~Strange that you should mention turnip pie... That remind me about my Aunt Marta...~
EXTERN BVALYGA TS496

CHAIN BJAN TS124
~Ma Jansen was never good with pies, you see. We always had to ask my aunt Marta (twice-removed aunt, mind you) to bake turnip pie for the Midwinter feast, as ma's pie usually ended up smelling of fish for some reason. Aunt Marta said once that it was because ma always puts fish in her turnip pie...~
EXTERN BVALYGA TS497

CHAIN BJAN TS125
~Ma got very cross because apparently that is her secret ingredient. They parted on the worst of terms and we never had Aunt Marta's turnip pie ever again.~
EXTERN BVALYGA TS498

CHAIN BJAN TS126
~But ma's baked turnip, braised turnip, fried turnip, turnip a-la-Rasheman, turnip stuffed with turnip and carrots are all pretty good...~
EXTERN BVALYGA TS499

CHAIN BJAN TS127
~See, Valygar, it reminded me the day when Uncle Podger... Oh, well. (*sighs*) It doesn't actually remind me of Uncle Podger at all. I loved... I love Lissa.~
EXTERN BVALYGA TS501

CHAIN BJAN TS128
~She loves him... Why, Valygar, why?~
EXTERN BVALYGA TS502

CHAIN BJAN TS129
~Yes, I guess so... That reminds me of my cousin Jen-Fer Jansen, who had fallen for this really tall and handsome ranger. But she was really short. She was a gnome, see? Of course he ignored her. So she went to the local witch and got a secret potion.~
EXTERN BVALYGA TS503

CHAIN BJAN TS130
~A secret potion to make him shorter.~
EXTERN BVALYGA TS504

CHAIN BJAN TS131
~Anyway, in the end she gave the potion to a big yellow dog to try if it worked. The dog had puppies and Jen-Fer made a fortune selling them as ladies' lap-doggies. It became all the rage. She and the witch now have a kennel and ship the puppies as far as Shou Lung.~
EXTERN BVALYGA TS505

CHAIN BJAN TS132
~Aye, Jen-Fer is. I wish my monkey smuggling business was as successful, but there is no market for monkeys lately, alas...~
EXTERN BVALYGA TS506

CHAIN BJAN TS133
~Now that reminds me my second cousin Amalia...~
EXTERN VPSIMB 51

CHAIN BJAN TS134
~Cousin Amalia? She did not have hair at all and wore a wig. But that did not hinder Amalia. She was a true femme fatale, just like you. You see, she was dreaming to give herself to a true artist, a man of inspiration and vision. "I shall fall in love because I fall in love" she was saying often. "And I can only fall in love with a great artist!" She wedded an old man.~
EXTERN VPSIMB 52

CHAIN BJAN TS135
~No, a turnip merchant. One of the most prominent in the trade, I must say. He had the biggest shop in the whole of Waterdeep and was exporting turnips as far as Rasheman. They eat plenty of turnip there.~
EXTERN VPSIMB 53

CHAIN BJAN TS136
~You see, she adored obstacles. The old rich man was the great obstacle on her way to true love. She was crying and acting all weird and saying that one day she is to find her true love and she will follow her calling for arts but until then she has too many obstacles. So when her husband died...~
EXTERN VPSIMB 54

CHAIN BJAN TS137
~No, she actually met another obstacle, poor soul.~
EXTERN VPSIMB 55

CHAIN BJAN TS138
~Indeed. Which reminds me...~
EXTERN VPSIMB 56

CHAIN BJAN TS139
~I was indeed. That's a craft we, the Jansens, possessed for many generations. This turnip I called Lissa. That pinkish shade on its sides reminds me of Lissa's cheeks. Just as plump too. Lissa was my fianc?e if you wish to know.~
EXTERN VPSIMB 58

CHAIN BJAN TS140
~Oh, poetry. That reminds me of the time Cousin Willy was writing that play of his. He said that the biggest problem is to get a captivating title. Uncle Lero said however that Cousin Willy's play would be just the same no matter what title he uses. So Cousin Willy called it "A Play Without a Name". Which apparently was a captivating title. Or so the critics said.~
EXTERN VPSIMB 59

CHAIN BJAN TS141
~Not exactly, the problem was that the general opinion was that the play failed to deliver what the captivating title promised. People were so mad that Cousin Willy switched the name to "A Lovestory of Teomund and Allastria Which Happened During the Times of Troubles in the Great and Prosperous City of Baldur's Gate Governed by the Most Respectable Dukes".~
EXTERN VPSIMB 60

CHAIN BJAN TS142
~Neither did the spectators. Imagine, they have to add twenty extra pages to the program, which in turn led to the shortage of paper and bread in Neverwinter and huge riots. Unfortunately because of these riots the playhouse was closed and Cousin Willy's play was prohibited.~
EXTERN VPSIMB 61