CHAIN BKORGAN TS134
~Shut your mouth, girl afore I shut it with me fist.~
EXTERN VPSIMB 17

CHAIN BKORGAN TS135
~Blasted fool! Think you can spit on me cause I take care of meself and not burden me head with worries of nonsense! I remember there was that priest of Ilmater, who thought to convert me...~
EXTERN VPSIMB 18

CHAIN BKORGAN TS136
~A dimwit more like. I hit low times and I told him, I'd go to his darned church and sleep there.~
EXTERN VPSIMB 19

CHAIN BKORGAN TS137
~I did not stay. I slept that night in the best inn!~
EXTERN VPSIMB 20

CHAIN BKORGAN TS138
~Some miserly Lord came by with a load of coin to donate to the priests. His sins were plugging him. So the idiot decided to give, not to take. I persuaded him to give... to me that is. Low times were over for Korgan. And he went straight to his god's arms, just as he desired.~
EXTERN VPSIMB 21

CHAIN BKORGAN TS139
~I love when they fight! Come, girl you want it, do not you?~
EXTERN VPSIMB 23

CHAIN BKORGAN TS140
~A man cannot go fighting without his ale, fool girl. Now, enough talking!~
EXTERN VPSIMB 24

CHAIN BKORGAN TS141
~Ooh! Yor hit a dwarf on the head! Ha-Ha-Ha! Yor have a lot to learn!~
EXTERN VPSIMB 25

CHAIN BKORGAN TS142
~Hot stuff!~
EXTERN VPSIMB 26

CHAIN BKORGAN TS143
~Fast learner! Ouch! That hurts! You're gonna suffer... Where is me axe? (*Tumbles over, hits the floor and starts snoring.*)~
EXTERN VPSIMB 271