CHAIN BMAZZY25 TS68
~That was a long time ago, Valygar. I believe that you said you would sleep on it. Well you have had much sleep since then, yet this is the first time you have brought the subject up.~
EXTERN BVALYG25 TS112

CHAIN BMAZZY25 TS69
~And you do not want to join with me. That is fine.~
EXTERN BVALYG25 TS113

CHAIN BMAZZY25 TS70
~Of course I will. I am a fair leader and I have no trouble recruiting. And there is something more I wanted to say, Valygar.~
EXTERN BVALYG25 TS114

CHAIN BMAZZY25 TS71
~Valygar, I love you both and I am sure you will be very happy together. I think I will hear one day some tales about you two.~
EXTERN BVALYG25 TS115

CHAIN BMAZZY25 TS72
~It's not at all like you to be so indecisive, Valygar.~
EXTERN BVALYG25 TS116

CHAIN BMAZZY25 TS73
~There is nothing greater than love, Valygar.~
EXTERN BVALYG25 TS117