APPEND BMAZZY

CHAIN BMAZZY TS127
~The spirit, Kachiko is not always coached from childhood... Sometimes it's like a fire breaking through no matter the attempts to extinguish it. A legend of great deeds, which I heard from a passing bard woke my heart. And I have followed the calling ever since. ~
EXTERN VPKACB 62

CHAIN BMAZZY TS128
~You are right. There was Patrick. He was a troubled kid, a funny sort... But I liked him a lot. We read together the books of old, going into all sorts of tricks to earn a gold piece a two for another tome. He... he ran away from home to become a sailor or some such and I could not let him do it on his own. Patrick was too... irresponsible. He needed someone to look after him, to keep him on the right track...~
EXTERN VPKACB 63

CHAIN BMAZZY TS129
~Anyway, that was my reason to leave Trademeet. It was awkward for a while, but now I cannot stop. I wish to see all of Faerun! I would like to journey to faraway lands, like Maztica or Kara-Tur! I just cannot stop. My biggest grief is that Patrick is with me no more...~
EXTERN BVALYGA TS153

CHAIN BMAZZY TS130
~That would be a grand thing to do.~
EXTERN BMAZZY TS131

CHAIN BMAZZY TS131
~Valygar, you shall come along too, my loyal squire.~
EXTERN BVALYGA TS154

CHAIN BMAZZY TS132
~Squire... Squire!~
EXTERN BVALYGA TS330

CHAIN BMAZZY TS133
~Are you always listening to my conversations with Valygar? I do not need your help to give him instructions, <CHARNAME>. You do not own him!~
EXTERN BVALYGA TS331

CHAIN BMAZZY TS134
~I know your name perfectly well, my loyal squire. Yet I did not start imagine that you preferred it over the title of a knight's squire.~
EXTERN BVALYGA TS332

CHAIN BMAZZY TS135
~I bet if it <CHARNAME> offered to let you be her squire, you'd be very willing.~
EXTERN BVALYGA TS333

CHAIN BMAZZY TS136
~<CHARNAME>, let me judge for myself when I need speak to my squire.~
EXTERN BVALYGA TS334

CHAIN BMAZZY TS137
~Oh, so you did hear me? You just decided not to answer my call?~
EXTERN BVALYGA TS335

CHAIN BMAZZY TS138
~Might I know why?~
EXTERN BVALYGA TS336

CHAIN BMAZZY TS139
~Typical! <CHARNAME> says a single word and she is tact and kindness and gentleness incarnate... whereas I am merely bossy and complaining. Might I remind you that it is I that watched your back and who protected from blows that were to injure you in the last battle...~
EXTERN BVALYGA TS337

CHAIN BMAZZY TS140
~I apologize then that I have disturbed you. You can return to what you were doing... Staring at <CHARNAME> I believe...~
EXTERN BVALYGA TS338

CHAIN BMAZZY TS141
~No, no. I am in fine condition, ready for battle as always!~
EXTERN BVALYGA TS340

CHAIN BMAZZY TS142
~I was thinking of someone... someone who is no longer with me... of Patrick. I miss him so much, Valygar. He was a wonderful person and a dear friend. I fell in love with him the day we met. Patrick could track an enemy tirelessly for days, he could fight like a lion, just like any other ranger, but he could also tell a story of old as if it happened before his very eyes...~
EXTERN BVALYGA TS341

CHAIN BMAZZY TS143
~Patrick was not a halfing. You know Valygar, just because we were lovers, everyone assumes that he was a halfing. He was a human.~
EXTERN BVALYGA TS342

CHAIN BMAZZY TS144
~Yes. You find that strange do you? That other races should find us, short people, attractive?~
EXTERN BVALYGA TS343

CHAIN BMAZZY TS145
~ Love should be reserved for tall and beautiful in the world of humans and elvenkind, is that it?~
EXTERN BVALYGA TS344

CHAIN BMAZZY TS146
~Maybe... you are somewhat similar... But... But that does not imply that I might be falling for you! Not at all. Do not even think of that.~
EXTERN BVALYGA TS345

CHAIN BMAZZY TS147
~Pap! It is common knowledge and plain as the nose on your face that you are partial to <CHARNAME>'s attentions...~
EXIT

CHAIN BMAZZY TS148
~None of them are here to trade a tale or share a glass of wine with. Shadows took them all.~
EXTERN VPSIMB 84

CHAIN BMAZZY TS149
~I was under the impression that you are a loner, Sime.~
EXTERN VPSIMB 85

CHAIN BMAZZY TS150
~So do I. To Patrick, my beloved!~
EXTERN VPSIMB 86

CHAIN BMAZZY TS151
~To Andrea and her little pseudo-dragon! I swear, I miss the little bugger.~
EXTERN VPSIMB 262

CHAIN BMAZZY TS152
~But of course the sword! Long had the slender and bright blades fascinated me. Look, how well balanced it is and how it flows lightly through the air. Is it not beautiful?~
EXTERN VPSIMB 88

CHAIN BMAZZY TS153
~Your voice is impartial, but I can see the glimmer in your eyes. You like swords, Sime Linvail.~
EXTERN VPSIMB 89

CHAIN BMAZZY TS154
~Of course. Still I reckon you a fierce adversary, no matter what you wield. Swords do not win battles. Fighters do.~
EXTERN VPSIMB 90

CHAIN BMAZZY TS155
~(*laughs*) Oh, that one! A wizards' toy!~
EXTERN VPSIMB 91

CHAIN BMAZZY TS156
~I wish I had been there to see it. Serves as a good warning. A good fighter shall not entrust his life to a magical trinket!~
EXTERN VPSIMB 92