CHAIN BMINSC TS99
~Boo says Kachiko is nice. I am looking for a big rounded purple bottle. The one, which makes people smart...~
EXTERN VPKACB 25

CHAIN BMINSC TS100
~Aye, Kachiko, the very same! See, when Dynaheir was alive, she told me that I could drink it and become smart, like Boo... But then she said: "Do not do it Minsc. You are a happy man, your heart tells you to defend the small and helpless and to strike evil. A smart man is never happy, because he does not trust his heart to know which butt is evil. Do you want to be unhappy, Minsc?"- That's what she said...~
EXTERN VPKACB 26

CHAIN BMINSC TS101
~Aye, but Boo says: "Minsc since Dynaheir dead, you are unhappy anyway. So why do not you become smart if you are already unhappy?"~
EXTERN VPKACB 27

CHAIN BMINSC TS102
~Regular hamsters - no, but Boo is the Giant Space Hamster! Now, why do I hold the potion bag?~
EXTERN VPKACB 28

CHAIN BMINSC TS103
~Yes! Let me stamp this skinny evil butt with my righteous boot!~
END
 ++ ~Calm down, all of you! We have enough enemies without starting to fight among ourselves!~ EXIT
 ++ ~Edwin, to be honest, you are wearing on my nerves also. I think we'd better part ways.~ EXTERN BEDWIN TS108
 ++ ~Speaking about violent death, Edwin, I killed you once and I shall do so again!~ EXTERN BEDWIN TS109

CHAIN BMINSC TS104
~Ah, my brother ranger, Boo wishes you to know he has observed your bravery in battle and is considering you for a knighthood into the Order of the Hamster.~
EXTERN BVALYGA TS359

CHAIN BMINSC TS105
~There is little you can hide from one so wise as Boo.~
EXIT

CHAIN BMINSC TS106
~(*Whispers*) Psst! Valygar! Heh, you is a sly one, ranger. Boo has sniffed out your attractiveness to <CHARNAME>. He lets me know that is beaming with approval for everyone. Hamsters, rangers, Bhaalspawn and all.~
EXTERN BVALYGA TS361

CHAIN BMINSC TS107
~Boo knows all, my woody brother. There is no secret, no matter how tiny - that is too small for Boo's wisdom to perceive.~
EXTERN BVALYGA TS362

CHAIN BMINSC TS108
~Boo is never wrong my foresty friend - he sees the future as well as your blushes.~
EXIT

CHAIN BMINSC TS109
~You put him down you, you, you! (*Minsc sputters inarticulately and snatches Boo away from Valygar before cradling him.*) You must not lay hands on Boo in this manner. There is no dignity in dangling by tails.~
EXTERN BVALYGA TS364

CHAIN BMINSC TS110
~Boo is not a pet! Boo is a wise and ancient being: small on the outside, large as a bear in the middle! He was just investigating if you are virginal, nothing to get so scared and tail-dangly about.~
EXTERN BVALYGA TS365

CHAIN BMINSC TS111
~You slippery fellow, you. Boo needs to be sure that <CHARNAME> 's husband to be is as clean as she is. Boo is very fond of her, you know.~
EXTERN BVALYGA TS366

CHAIN BMINSC TS112
~Boo is not small, Sime. Boo is a Miniature Giant Space Hamster. He is incredibly large for his very young age. And he is not pitiful! Have not you seen how he hungers for a battle?~
EXTERN VPSIMB 208

CHAIN BMINSC TS113
~And after the battle is won he is the first one to drink the blood of our defeated enemies!~
EXTERN VPSIMB 209

CHAIN BMINSC TS114
~Yes! Boo learns the ferocity from Minsc! And he gives Minsc his wise counsel in return.~
EXTERN VPSIMB 210

CHAIN BMINSC TS115
~Boo says that he likes what Lady Sime says about him. He says that Lady Sime has eyes like stars.~
EXTERN VPSIMB 212

CHAIN BMINSC TS116
~Actually he said "as pretty as a hamster's" but I thought "like stars" would be better. It is better, is it not?~
EXTERN VPSIMB 213

CHAIN BMINSC TS117
~Ahem, Lady Sime, I am not sure that I know. Did you like what Boo said or did you like what Minsc said?~
EXTERN VPSIMB 214

CHAIN BMINSC TS118
~He is just shy, Lady Sime. Now, Boo, be a good hamster, go sit with Lady Sime, and tell her all the nice things you wanted to tell her.~
EXTERN VPSIMB 267

CHAIN BMINSC TS119
~Can I talk to you about Boo?~
EXTERN VPSIMB 217

CHAIN BMINSC TS120
~Boo wants to know what happened when you took him from me.~
EXTERN VPSIMB 218

CHAIN BMINSC TS121
~I... fainted?~
EXTERN VPSIMB 219

CHAIN BMINSC TS122
~I will not, Lady Sime.~
EXTERN VPSIMB 220

CHAIN BMINSC TS123
~Boo's saying that if I tell you, it would not be a secret place.~
EXTERN VPSIMB 222

CHAIN BMINSC TS124
~Minsc does not want Lady Sime to be dead. Boo would be very sad.~
EXTERN VPSIMB 223

CHAIN BMINSC TS125
~Boo is not sure it is a good idea. Lady Sime should not go up front. It is dangerous for Lady Sime. Lady Sime should stay behind Minsc and throw stones.~
EXTERN VPSIMB 224

CHAIN BMINSC TS126
~Dirty tricksters would die once Minsc unleashed his righteous boot on them! But Boo thinks you are right. Here is your mace, Sime.~
EXTERN VPSIMB 225

CHAIN BMINSC TS127
~Yes, Sime. I protected Dynaheir. That was my duty. But I failed it. Irenicus killed Dynaheir and I failed my dajemma. Now I have only Boo to defend.~
EXTERN VPSIMB 227

CHAIN BMINSC TS128
~That it was, but the mage tricked us! He did not face us and he avoided the battle, that coward. He had us poisoned! And then he killed Dynaheir. You are not like Dynaheir, Sime. Boo says I can protect you, but you are not a witch. That's mean I can think of you as a non-witch even if I do protect you.~
EXTERN VPSIMB 228

CHAIN BMINSC TS129
~Boo says if you are not a witch then I am not prohibited to love you. I was not allowed to love Dynaheir, only protect her, because she was my witch.~
EXTERN VPSIMB 229

CHAIN BMINSC TS130
~Sime, Boo says if I am to court a lady properly, I am to give her little gifts. He says a carrot would be good. Will you take the carrot?~
EXTERN VPSIMB 231

CHAIN BMINSC TS131
~But I thought that carrots are not very pretty. Ladies like pretty things.~
EXTERN VPSIMB 232

CHAIN BMINSC TS132
~Do you like ugly things?~
EXTERN VPSIMB 233

CHAIN BMINSC TS133
~I wanted to give you a gem, but all the gems we are getting are already in our bags so you have them anyway. I have this little round pebble. It is not a precious stone, but I like it. I think it is pretty. I want to give it to you.~
EXTERN VPSIMB 234

CHAIN BMINSC TS134
~Of course! Nobody before wanted to talk to Boo. Strange, no? Here, I will hold it in my palms and you need to put your ear closer. He has very quiet voice, Boo.~
EXTERN VPSIMB 236

CHAIN BMINSC TS135
~Beautiful Sime wants to talk to Boo? Poi... poin...~
EXTERN VPBOO 5

CHAIN BMINSC TS136
~Yes, you have it! Smart Boo! Boo is so smart, Lady Sime, no?~
EXTERN VPBOO 6

CHAIN BMINSC TS137
~Little Boo is tired? Boo, do you want cheese? Aye, not very polite of you to stop talking to Lady Sime like that, Boo.~
EXTERN VPSIMB 243

CHAIN BMINSC TS138
~Yes, yes. I shall settle him to sleep in his little woolen sock. Then he will rest well and be as ferocious as ever in the next battle.~
EXTERN VPSIMB 244

CHAIN BMINSC TS139
~Are you talking to Boo about love Sime? I did not listen, just heard "love".~
EXTERN VPSIMB 251

CHAIN BMINSC TS140
~Oh, my little Boo is such a kidder!~
EXTERN VPSIMB 256

CHAIN BMINSC TS141
~Do not get all fluffy and upset, Boo. You know that your name is noble. Very noble.~
EXTERN VPBOO 18

CHAIN BMINSC TS142
~There was that hero of old, great king.~
EXTERN VPBOO 19

CHAIN BMINSC TS143
~No, why in Rasheman?~
EXTERN VPBOO 20

CHAIN BMINSC TS144
~The great king... ahem, knight fought some strange battle, when there are no enemy.~
EXTERN VPBOO 21

CHAIN BMINSC TS145
~The knight was very brave, and kicked all enemies. Than he was a winner. He went to take the wreath from the pretty girl. But Lady Sime is prettier.~
EXTERN VPBOO 22

CHAIN BMINSC TS146
~But than a hamster ran. Girl got scared and fell. The knight was very tired and fell too.~
EXTERN VPBOO 23

CHAIN BMINSC TS147
~The king laughed and announced the hamster the winner of the tournament 'cause he made the best knight to fall from the saddle.~
EXTERN VPBOO 24

CHAIN BMINSC TS148
~Because the man who sold Boo to me called him Boo.~
EXTERN VPSIMB 261