CHAIN BNALIA25 TS59
~Is not it ironic that the safest place for us is the Nine Hells itself?~
EXTERN BVALYG25 TS202

CHAIN BNALIA25 TS60
~And I thought it was bad enough to inherit the grim Castle as my Keep! I shudder when I think that <CHARNAME> might have to live in this place permanently if she... you know... ascends.~
EXTERN BVALYG25 TS203

CHAIN BNALIA25 TS61
~Well, it might be redone, I guess. Couple of bright color spots, may be a painting or two to decorate those gray walls? Large Shou Lung vases on the floor would do nicely to chase the shadows from the corners. Also she might want to trim Cespenar a bit...~
EXTERN BVALYG25 TS204

CHAIN BNALIA25 TS62
~It does sound odd, but I will find the place a bit friendlier and less frightening if something like that was done. I know, it is still the Nine Hells part and its grim nature will not change.~
EXIT