CHAIN BNALIA TS51
~No, Kachiko, how can you say so? I hate this dress! My aunt made me wear it when I was in the Castle. I had to hurry when trolls attacked... So I could not change. Your clothes are simple, yet so elegant. The cut, the embroidery! The color makes you look like... like...~
EXTERN BYOSHIM TS104

CHAIN BNALIA TS52
~May be... Or peach... Believe me, Kachiko; many ladies in Athkatla would sell their soul to appear as young and beautiful as you... But they cannot, these painted and perfumed snobs!~
EXTERN VPKACB 30

CHAIN BNALIA TS53
~A poor woman working endless hours, loosing her eyesight, her back forever bent, and her fingers disfigured by needles, sewed this dress... No, Kachiko, I prefer your simple and honest dress and I hate mine.~
EXIT

CHAIN BNALIA TS54
~My aunt is known in the certain circles of Athkatla, but I would not call her infamous, Valygar.~
EXTERN BVALYGA TS539

CHAIN BNALIA TS55
~No! Of course not! I could not imagine that Auntie even knows where Slums are.~
EXTERN BVALYGA TS540

CHAIN BNALIA TS56
~What... what are you talking about, Valygar?~
EXTERN BVALYGA TS541

CHAIN BNALIA TS57
~This cannot be...~
EXTERN BVALYGA TS542

CHAIN BNALIA TS58
~Did he... did he die?~
EXTERN BVALYGA TS543

CHAIN BNALIA TS59
~Is this even true?~
EXTERN BVALYGA TS544

CHAIN BNALIA TS60
~We still should try to support less fortunate. Why would not we donate some money to a temple of Ilmater if we do not have time for helping out ourselves?~
EXTERN BVALYGA TS546

CHAIN BNALIA TS61
~I love the Keep, Sime. I spent all my childhood there and I have many fond memories of my relatives and friends coming to visit us there. But of course I cannot help but to feel guilty that my family owns such an excessive space when the less fortunate have no roof over their head.~
EXTERN VPSIMB 74

CHAIN BNALIA TS62
~As a matter of fact I have very definite plans for the Keep. In the Northern wing I shall create a school for the village kids and I plan to re-arrange the whole of the first floor into a charitable hospital. I have corresponded with few priests of Ilmater and few missionaries are willing to help me to start both the school and the hospital.~
EXTERN VPSIMB 75

CHAIN BNALIA TS63
~I love the Keep, Sime. I spent all my childhood there and I have many fond memories of my relatives and friends coming to visit us there.~
EXTERN VPSIMB 77

CHAIN BNALIA TS64
~I do not really mourn the material loss, Sime. What bothers me is that my plans for the Keep were ruined. In the Northern wing I wanted to create a school for the village kids and I planned to re-arrange the whole of the first floor into a charitable hospital. Now none of it's going to happen!~
EXTERN VPSIMB 78

CHAIN BNALIA TS65
~I do not quite recognize you, Sime. The crimson cloak, jewelry, and I if I am not mistaken some make up...~
EXTERN VPSIMB 80

CHAIN BNALIA TS66
~Which one would that be? I reckoned of none.~
EXTERN VPSIMB 81

CHAIN BNALIA TS67
~(*Laughs*) They take you for an empty headed noble, do they not?~
EXTERN VPSIMB 82