CHAIN BVICONI TS575
~The surface... what a stupid place! Here, in Amn, you are a strong and valiant warrior. In your homeland you'd be subservient to some lowly jaluk. Stupid place.~
EXTERN VPKACB 32

CHAIN BVICONI TS576
~Do not think me a fool. In Kara-Tur women are slaves of men... The ones who sell themselves are considered to be "free"!~
EXTERN VPKACB 33

CHAIN BVICONI TS577
~What about you, Kachiko? Are you trying to find a lover to gain power?~
EXTERN VPKACB 34

CHAIN BVICONI TS578
~I do not understand you. If the only place to find power is some jaluk's bed that's where I would be...~
EXTERN VPKACB 35

CHAIN BVICONI TS579
~I care not for your displeasure. When female desires to watch a male he should be grateful of attention and shiver with delight and anticipation of an order.~
EXTERN BVALYGA TS392

CHAIN BVICONI TS580
~That's because you are a fool, rivvin. I can see now why <CHARNAME> would take an interest in you. Such a pleasure is torturing a bold male...~
EXTERN BVALYGA TS393

CHAIN BVICONI TS581
~You are sad and pathetic, male. You see not the obvious. You refute what could be your greatest chance to change your lowly station. I shall not spare you any more of my time, rivvin.~
EXTERN BVALYGA TS394

CHAIN BVICONI TS582
~Oh, the male is rude. Were we in Menzoberranzan, I'd beat you to death for a tenth of this insult. But you would not dare even look at me, let alone speak to me there. You would crawl by my feet and beg for my attention.~
EXTERN BVALYGA TS396

CHAIN BVICONI TS583
~Do you even know what desire is? The longer I watch you, the firmer is my conviction that you are no man's friend and no woman's lover. Fury and emptiness you are.~
EXTERN BVALYGA TS397

CHAIN BVICONI TS584
~I am bored and I will accept an inadequate substitute, such as an ungraceful human.~
EXTERN BVALYGA TS398

CHAIN BVICONI TS585
~Valygar? (*catches his sleeve*)~
EXTERN BVALYGA TS399

CHAIN BVICONI TS586
~You will regret this! I hate you!~
EXTERN BVALYGA TS400

CHAIN BVICONI TS587
~Silence, male. I have decided that you will deliver me some pleasure tonight. That's of course if your clumsiness is bearable...~
EXTERN BVALYGA TS476

CHAIN BVICONI TS588
~What that has to do with my order?~
EXTERN BVALYGA TS477

CHAIN BVICONI TS589
~So if mutual hate forbids surfacers to become lovers, mutual love shall promote it?~
EXTERN BVALYGA TS478

CHAIN BVICONI TS590
~Then why are you not laying by <CHARNAME>'s side?~
EXTERN BVALYGA TS479

CHAIN BVICONI TS591
~Do you hate her?~
EXTERN BVALYGA TS480

CHAIN BVICONI TS592
~Does she hate you?~
EXTERN BVALYGA TS481

CHAIN BVICONI TS593
~So?~
EXTERN BVALYGA TS482

CHAIN BVICONI TS594
~You are a hypocrite and a liar, male. I may not know much of the surfacers but I know desire when I see it. Now, leave this pointless argument and do what I ordered you.~
EXTERN BVALYGA TS483

CHAIN BVICONI TS595
~Shut up, rivvin! I am going to tell you something you want to hear.~
EXTERN BVALYGA TS485

CHAIN BVICONI TS596
~You say your blood is cursed by a hereditary affliction to dark magic. <CHARNAME> says that her dark ancestry taints her blood.~
EXTERN BVALYGA TS486

CHAIN BVICONI TS597
~Blood against blood, taint against taint. Which should win? Do you think Corthala's blood is stronger than Bhaal's? Do not you think that your precious magical curse will be burnt out of the veins of a child should it mix with a god's blood?~
EXTERN BVALYGA TS487

CHAIN BVICONI TS598
~No, no. You are not afraid of the curse. You are simply an impotent, miserable, scared male who is incapable of touching a woman.~
EXTERN BVALYGA TS488

CHAIN BVICONI TS599
~There is a sweet torture to see a winner and her prize burn. I had a husband once and I caught him with my sister. I burnt them. I still can see the flames licking their corpses. Shaar was smiling that day on me.~
EXTERN BVALYGA TS489

CHAIN BVICONI TS600
~(*laughs*) The one you cherish is no better than I. Think about what I have said about the taint, ranger.~
EXTERN BVALYGA TS490

CHAIN BVICONI TS601
~Why you are going away from the Shadow Thieves Guild? You do not look stupid to me, and yet your actions are inapt. In your absence another would usurp your rightful place by your father.~
EXTERN VPSIMB 94

CHAIN BVICONI TS602
~You find it more desirable to crawl through the dirty streets and be treated like rubbish by every rivvin you meet and still have no station?~
EXTERN VPSIMB 95

CHAIN BVICONI TS603
~(*snorts*) And they will get it, no doubt. Typical. Imbecilic surfacers.~
EXTERN VPSIMB 96

CHAIN BVICONI TS604
~Very few. Lloth is a cunning Mistress and watches her herd carefully. The high priestesses are ever restless, hunting the outlaws to sacrifice to Lloth and gain her favor.~
EXTERN VPSIMB 98

CHAIN BVICONI TS605
~I know of none. Drizzt * spits * brought misfortune and ill fate to all of the Menzoberranzan. I doubt that anyone would feel anything but loathing for him and his choices. Drizzt's treachery strengthened my people's resolve to keep to their own ways.~
EXTERN VPSIMB 99

CHAIN BVICONI TS606
~If you wish for me to answer to all of my kin's doings, you are too late. You should have thrown a torch into my pyre.~
EXTERN VPSIMB 100

CHAIN BVICONI TS607
~(*Hisses and tries to stab Sime*)~
END
 ++ ~What is going on? I did not think you were such close friends to stay up late and chat.~ EXTERN VPSIMB 577
 ++ ~Can I ever get any sleep around here? Viconia, Sime, break it!~ EXTERN VPSIMB 577
 ++ ~What in Nine Hells is going on?~ EXTERN VPSIMB 577

CHAIN BVICONI TS608
~Shut up mrannd d'ssins. Rivvin.~
END
 ++ ~Viconia, that's it. I have given you shelter against fanatics and how do you repay me? By trying to kill the woman I love?~ EXTERN VPSIMB TS609
 ++ ~Viconia, get you backpack and go away. Now!~ EXTERN VPSIMB TS610

CHAIN BVICONI TS609
~Jal ssinrig zhah waella - All love is foolish.~
END
 ++ ~No it is not. You are wrong, have not I taught you anything? (*sighs*) Oh, Viconia. I guess it is my own fault, I should not have spend so much time with another and give your poor lost heart so much troubles. Sime, I am sorry about what have happened. I am sure you have it in you to forgive both Viconia and myself. I should not have abandoned the road I walked with Viconia.~ EXTERN VPSIMB 578
 ++ ~Whatever you say, Viconia. But do not you dare to as much as look at Sime unfriendly again! I am sorry that you have suffered from that vile woman, Sime. Be strong, my love.~ EXTERN VPSIMB 579

CHAIN BVICONI TS610
~I was going to. (*laughs*) But I wanted to kill your blonde first. Ssun usst - fear me!~
DO ~SetGlobal("ViconiaRomanceActive","GLOBAL",3) LeaveParty() EscapeArea()~
EXIT