CHAIN BYOSHIM NEJ8
~What I had learnt cherry blossom? I could only stand in amazement at what you had learnt! I am sure you didn't learn that on Kara Tur!~
EXTERN VPKACB NEJ1

CHAIN BYOSHIM NEJ9
~(*Bows to Kachiko*) Will the lovely Kachiko put away her swords for one night and take the hand of Yoshimo in them instead?~
EXTERN VPKACB NEJ2

CHAIN BYOSHIM NEJ10
~Then you are in for a pleasant surprise my cherry blossom for I have learnt many things in my absence. The pleasure that comes from dancing with a beautiful girl for one... what does this beautiful girl say?~
EXTERN VPKACB NEJ3

CHAIN BYOSHIM TS84
~Ouch! A moment to catch my breath, fierce warrior!~
EXTERN VPKACB 1

CHAIN BYOSHIM TS85
~I have a rule to watch anyone who tried to kill me once. A very sensible rule, my cherry blossom. But I must admit it had been a chore before, not a pleasure.~
EXTERN VPKACB 2

CHAIN BYOSHIM TS86
~I was just trying to be entertaining, cherry blossom... Ouch! In gratitude for the informative fencing lesson... I have learnt that Kachiko does not like cherries, for example. Ouch! Ouch! Oh, I think <CHARNAME> is saying the break is over... Unfortunately, we have to stop the training for now...~
DO ~RestParty()~
EXIT

CHAIN BYOSHIM TS87
~I must say that sneaking away from you was becoming increasingly difficult. You were as a spirited young girl so fond of her older brother and you followed him as a shadow. I was very nearly crossed with you once, Kachiko.~
EXTERN VPKACB 4

CHAIN BYOSHIM TS88
~There was no other way. Naoko and I were very young and you know first-hand how hostile our families are towards each other. If our friendship were discovered, it would have terrible consequences, well at least terrible for boys of our age.~
DO ~RestParty()~
EXIT

CHAIN BYOSHIM TS89
~I fled our village and got on the ship sailing for far away Faerun. The rest is history.~
EXTERN VPKACB 6

CHAIN BYOSHIM TS90
~It is not a bedtime story, Kachiko. The world is a cold place for a boy running from home because he was accused of murdering his best friend. Later, in Faerun, I was shunned, beaten and taunted for looking and speaking differently...~
EXTERN BYOSHIM TS91

CHAIN BYOSHIM TS91
~Well, on the bright side, being young and exotic can earn you few coins from bored rich ladies... Curse my long tongue! Kachiko, I am sorry...~
EXTERN VPKACB 8

CHAIN BYOSHIM TS92
~Not the destitute rogue I had become? When I look in those shiny eyes of yours I wish to tell you that I braved the fortune and became a pure-hearted paladin or a noble ranger... But I did not, Cherry Blossom. I am Yoshimo Hashimoto, a bounty hunter.~
EXIT

CHAIN BYOSHIM TS93
~Cherry Blossom, our last conversation keeps nagging me. The way you said "honorable noble"... I remember craving honor. Until I stared in Naoko's dead face and realized that one of my own "honor-bound" kin must have killed him. I do not believe in honor any more.~
EXTERN VPKACB 10

CHAIN BYOSHIM TS94
~Indeed. I saw purest honor in a fiery maiden who put her sword away and agreed to listen to one whom she hated and had judged to be guilty...~
EXTERN VPKACB 11

CHAIN BYOSHIM TS95
~No, Kachiko. You are mistaken. I had done something terrible, which robbed me of honor forever. In a moment of weakness, I allowed a creature of pure evil to despoil my soul. I never thought I'd become a traitor, yet I am. Please, do not ask anymore, Kachiko, for I do not wish to cast a shade on your innocent heart.~
EXTERN VPKACB 12

CHAIN BYOSHIM TS96
~No, Kachiko, what's done cannot be undone. I will not allow you to be touched by my curse and my taint. That much I can do.~
DO ~SetGlobalTimer("VP_KachikoRomance","GLOBAL",ONE_DAY)~
EXIT

CHAIN BYOSHIM TS97
~Here, take my cloak. The nights are so much colder here than in Kara-Tur. It took me long to get used to it too...~
EXTERN VPKACB 14

CHAIN BYOSHIM TS98
~Of course! You know my (whispers dramatically) darkest secret...~
EXTERN VPKACB 15

CHAIN BYOSHIM TS99
~Yes, Kachiko, I was only joking. Now sleep well, dear child (tucks the cloak around her). I was only joking...~
DO ~RestParty()~
EXIT

CHAIN BYOSHIM TS100
~Look at Kachiko, Anomen! She is poetry herself; I just copy her to the paper:

Like cherry blossom,
beautiful Kachiko
is among us...~
EXTERN BANOMEN TS588

CHAIN BYOSHIM TS101
~Eh, it's finished actually...~
EXTERN BANOMEN TS589

CHAIN BYOSHIM TS102
~My cherry blossom...~
EXTERN BANOMEN TS590

CHAIN BYOSHIM TS103
~Women...~
EXIT

CHAIN BYOSHIM TS104
~Cherry Blossom, Lady Nalia?~
EXTERN BNALIA TS52

CHAIN BYOSHIM TS105
~How about witnessing a blade by your neck, poet?~
EXTERN BHAERDA TS167

CHAIN BYOSHIM TS106
~What are you two arguing about?~
EXTERN VPKACB 54

CHAIN BYOSHIM TS107
~That does it! I will not allow you to speak like that to Kachiko!~
EXTERN VPKACB 57

CHAIN BYOSHIM TS108
~I was drunk.~
EXTERN VPKACB 73

CHAIN BYOSHIM TS109
~And that was my answer. I was drunk. I was disgusted with myself. Once a city guard gave me a job to trace a man who was a suspected rapist. I found him easily and brought to the Magistrate. The man was immediately sentenced and thrown into the prison. Later I heard that he hanged himself in jail and that his only fault was that he found the favor of a general's daughter, but did not have the approval of the general.~
EXTERN VPKACB 74

CHAIN BYOSHIM TS110
~I never bothered to check the city guard's story and I felt like a fool. I did not listen to the poor man's words; I just trusted the authorities. I did my job and I got paid. An innocent man died. So I got drunk. Then Irenicus showed up with his malicious tongue. He understood my mood quickly and before I knew it I was hanging to his every word and he convinced me that the world is one big snake pit... Do you want me to continue?~
EXTERN VPKACB 75

CHAIN BYOSHIM TS111
~I was weak, Kachiko. But everything that has happened since gave me new strength and new faith... you, Kachiko. And I swear to you, no lie will fool me again.~
EXIT

CHAIN BYOSHIM TS112
~Are you courting Kachiko, Valygar? Do not try anything stupid.~
EXTERN BVALYGA TS411

CHAIN BYOSHIM TS113
~Kachiko?~
EXTERN VPKACB 84

CHAIN BYOSHIM TS114
~Valygar is saying your heart is beyond reach. I shall warn you that some men in these parts of the world are not honorable. Please, be careful in choosing.~
EXTERN VPKACB 85

CHAIN BYOSHIM TS115
~No! You are not doing anything that dangerous! Unless it is a very small cliff and I stand underneath it to supervise your jump and to catch you.~
EXTERN VPKACB 86

CHAIN BYOSHIM TS116
~Do not be a bore, Valygar, tell us all a tale. You must know hundreds from your time spent wandering the land.~
EXTERN BVALYGA TS517

CHAIN BYOSHIM TS117
~That is a great disappointment ranger, next time I will insist.~
EXTERN BVALYGA TS518

CHAIN BYOSHIM TS118
~Now Valygar, you have had time to decide upon a tale to tell us. There must surely be many bizarre yarns in your family's chronicles.~
EXTERN BVALYGA TS520

CHAIN BYOSHIM TS119
~Surely you cannot mean that you would frighten us all to death?~
EXTERN BVALYGA TS521

CHAIN BYOSHIM TS120
~I apologise my friend. We all need a good night's sleep.~
EXTERN BVALYGA TS522

CHAIN BYOSHIM TS121
~Yet I have no doubts that you'd press on for as long as needed. I wonder at the spirit which is so strong in such a delicate body.~
EXTERN VPKAC25B 1

CHAIN BYOSHIM TS122
~Fiery maiden, your anger is in vain for I love you all the more for it. I love that you are different from what I was taught to treasure in a woman: the ideal wife shall be obedient, defenseless and rely on her husband to survive. More nonsense invented by old fools and repeated by young fools from generation to generation.~
EXTERN VPKAC25B 2

CHAIN BYOSHIM TS123
~Kachiko, ever since your family kidnapped you, I have been thinking of a way to prevent an incident like this happening in the future...~
EXTERN VPKAC25B 4

CHAIN BYOSHIM TS124
~And I came to the conclusion, that I need to stay by your side day and night to guard you.~
EXTERN VPKAC25B 5

CHAIN BYOSHIM TS125
~Cherry blossom let me try it in another way then. (Yoshimo goes to his knees): Kachiko, the moment I saw you I wished for us to be together. You are the first woman I love and I feel inseparable from. Would you accept my plea and allow me to stay by your side tonight, Kachiko?~
EXTERN VPKAC25B 6

CHAIN BYOSHIM TS126
~I just put on my most serious mask, my cherry blossom...~
EXTERN VPKAC25B 7

CHAIN BYOSHIM TS127
~Yes, cherry blossom.~
EXTERN VPKAC25B 9

CHAIN BYOSHIM TS128
~I saw it for sale at the local market and I acquired it. Are you interested in more details about my... hmm... purchase or do you want to join me in returning the freedom to this wondrous being?~
EXTERN VPKAC25B 10

CHAIN BYOSHIM TS129
~As the wisest of our ancestors did.~
EXTERN VPKAC25B 11

CHAIN BYOSHIM TS130
~And may they smile at Kachiko and grant her happiness...~
EXTERN VPKAC25B 12

CHAIN BYOSHIM TS131
~I'll spare you this time, ranger. Cherry Blossom, you embarrass Valygar.~
EXTERN VPKAC25B 20

CHAIN BYOSHIM TS132
~Yes you do. After all, it is a private matter.~
EXTERN VPKAC25B 21

CHAIN BYOSHIM TS133
~(*sighs*) You and <CHARNAME> of course.~
EXTERN BVALYG25 TS150

CHAIN BYOSHIM TS134
~Did he come one day as far as my land?~
EXTERN BVALYG25 TS197

CHAIN BYOSHIM TS135
~That is a rare and magnificent weapon, Valygar.~
EXTERN BVALYG25 TS198

CHAIN BYOSHIM TS136
~Yes, Valygar. They read... To a warrior pure... You look surprised, Valygar.~
EXTERN BVALYG25 TS199

CHAIN BYOSHIM TS137
~But it referred to its owner. A gift from a lady or a comrade at arms mayhap?~
EXTERN BVALYG25 TS200

CHAIN BYOSHIM TS138
~Mayhap I admire the sight in front of me. Exquisite is your beauty, Sime, and perfect is your grace.~
EXTERN VPSIMB 63

CHAIN BYOSHIM TS139
~(*bows*) You know more than you are willing to tell as well, Lady Sime.~
EXTERN VPSIMB 64

CHAIN BYOSHIM TS140
~Then tell me, my direct and honest Sime, what interest Linvail has in <CHARNAME>?~
EXTERN VPSIMB 65

CHAIN BYOSHIM TS141
~Linvail wanted you, his most trusted ally, to follow <CHARNAME>.~
EXTERN VPSIMB 66

CHAIN BYOSHIM TS142
~And yet you are the only one who would mourn his death, Sime. That's an ally.~
EXTERN VPSIMB 67

CHAIN BYOSHIM TS143
~Somehow the words of milady sound like a scold. Did you mean it to be a compliment?~
EXTERN VPSIMB 69

CHAIN BYOSHIM TS144
~You have no love for thieves, I take it? Why so? You must have seen deserving ones among Aran's cohorts.~
EXTERN VPSIMB 70

CHAIN BYOSHIM TS145
~Think what you may, Sime, but sometimes stealing means survival. Poor people had loved a thief or two more than they loved their lords. Noble lords turn thieves sometimes.~
EXTERN VPSIMB 71

CHAIN BYOSHIM TS146
~Each tale has a grain of truth.~
EXTERN VPSIMB 72