BEGIN VPYOS25B

CHAIN VPYOS25B 0
~Yet I have no doubts that you'd press on for as long as needed. I wonder at the spirit which is so strong in such a delicate body.~
EXTERN VPKAC25B 1

CHAIN VPYOS25B 1
~Fiery maiden, your anger is in vain for I love you all the more for it. I love that you are different from what I was taught to treasure in a woman: the ideal wife shall be obedient, defenseless and rely on her husband to survive. More nonsense invented by old fools and repeated by young fools from generation to generation.~
EXTERN VPKAC25B 2

CHAIN VPYOS25B 2
~Kachiko, ever since your family kidnapped you, I have been thinking of a way to prevent an incident like this happening in the future...~
EXTERN VPKAC25B 4

CHAIN VPYOS25B 3
~And I came to the conclusion, that I need to stay by your side day and night to guard you.~
EXTERN VPKAC25B 5

CHAIN VPYOS25B 4
~Cherry blossom let me try it in another way then. (Yoshimo goes to his knees): Kachiko, the moment I saw you I wished for us to be together. You are the first woman I love and I feel inseparable from. Would you accept my plea and allow me to stay by your side tonight, Kachiko?~
EXTERN VPKAC25B 6

CHAIN VPYOS25B 5
~I just put on my most serious mask, my cherry blossom...~
EXTERN VPKAC25B 7

CHAIN VPYOS25B 6
~Yes, cherry blossom.~
EXTERN VPKAC25B 9

CHAIN VPYOS25B 7
~I saw it for sale at the local market and I acquired it. Are you interested in more details about my... hmm... purchase or do you want to join me in returning the freedom to this wondrous being?~
EXTERN VPKAC25B 10

CHAIN VPYOS25B 8
~As the wisest of our ancestors did.~
EXTERN VPKAC25B 11

CHAIN VPYOS25B 9
~And may they smile at Kachiko and grant her happiness...~
EXTERN VPKAC25B 12

CHAIN VPYOS25B 10
~I'll spare you this time, ranger. Cherry Blossom, you embarrass Valygar.~
EXTERN VPKAC25B 20

CHAIN VPYOS25B 11
~Yes you do. After all, it is a private matter.~
EXTERN VPKAC25B 21

CHAIN VPYOS25B 12
~(*Sighs*) You and <CHARNAME> of course.~
EXTERN BVALYG25 TS150