BEGIN LOVEONE6

CHAIN
IF ~NumTimesTalkedTo(0)~ THEN LOVEONE6 0
~Sime Linvail... I was afraid that I would never see you again.~
EXTERN VPSIM25J TSTOB1

CHAIN LOVEONE6 1
~What is there to understand? I came to ask you why did you kill me?~
EXTERN VPSIM25J TSTOB2

CHAIN LOVEONE6 2
~Recklessness... Darling, I only became reckless, when I understood that you would give your heart to anyone, but me.~
EXTERN VPSIM25J TSTOB3

CHAIN LOVEONE6 3
~But you did not love me. Funny how it still hurts to see you with another <PRO_MANWOMAN>... just like it did in life.~
EXTERN VPSIM25J TSTOB4

CHAIN LOVEONE6 4
~And I loved you madly. I loved you so much that I did not want to live if you did not return my feelings... so I chose to fight as I was a berserker... sooner or later I knew that the death will find me...~
EXTERN VPSIM25J TSTOB5