BEGIN LOVEONE5

CHAIN
IF ~NumTimesTalkedTo(0)~ THEN LOVEONE5 0
~Valygar? Is it you... did you return at last, my love?~
EXTERN VALYG25J TS27

CHAIN LOVEONE5 1
~Why did not you come sooner? I died lonely, waiting for you...The waiting killed me...~
EXTERN VALYG25J TS28

CHAIN LOVEONE5 2
~You never forgave, did not you? Your eyes are so cold...~
EXTERN VALYG25J TS29

CHAIN LOVEONE5 3
~No, we could not have. You did not love me any more. You came back fulfilling your duty, no more. When I saw it, I lied to you! And I died then. I turned into a shadow. You killed me, not the Shade Lord...~
EXTERN VALYG25J 1