BEGIN OTAKO

CHAIN
IF ~NumberOfTimesTalkedTo(0)~ THEN OTAKO 0
~Yoshimo-san. My great pleasure is to see you again. Uncle often said you will return to help your family and so you did.~
EXTERN YOSHJ TS173

CHAIN OTAKO 1
~Your father will explain the things happening around here to you better than I can. Hashimoto's stronghold is just to the east and south from here. Hurry there Yoshimo, for we need help. And you can kill the Nakanishi wench, you have captured. There is no law above us any more but the honor of Hashimoto.~
EXTERN YOSHJ TS174

CHAIN OTAKO 2
~As you wish, Yoshimo-san. But you should remember that "one must aim not to disappoint his father." Have you forgotten the teachings of our ancestors in the strange lands?~
EXTERN YOSHJ TS175

CHAIN OTAKO 3
~Ha-ha-ha...(*laughs madly*)~
DO ~EscapeArea()~
EXTERN VPKACJ N20