BEGIN VAMPSIME

CHAIN VAMPSIME 0
~As you desire Mistress. (*Sime tries to walk towards you, hissing some threat, but stops short in her steps.*)~
EXTERN VAMPSIME 1

CHAIN VAMPSIME 1
~I cannot hurt <CHARNAME> Mistress. I cannot... I will take anybody's life but not his. Please, Mistress, forgive me my disobedience... punish me if you will, destroy me, but I will not harm him. I love him.~
EXTERN C6BODHI TS33