EXTEND_BOTTOM C6ELHAN2 70
  IF ~PartyHasItem("misc7l")~ THEN REPLY ~Elhan! I've the half vampire body of Valygar here because of you! You'll tell me now!~ EXTERN C6ELHAN 76
  IF ~PartyHasItem("miscbsim")~ THEN REPLY ~Elhan! I've the half vampire body of Sime here because of you! You'll tell me now!~ EXTERN C6ELHAN 76
  IF ~PartyHasItem("miscbkel")~ THEN REPLY ~Elhan! I've the half vampire body of Keldorn here because of you! You'll tell me now!~ EXTERN C6ELHAN 76
  IF ~PartyHasItem("miscblei")~ THEN REPLY ~Elhan! I've the half vampire body of Leina here because of you! You'll tell me now!~ EXTERN C6ELHAN 76
END