IF
	Global("AttackedThieves","GLOBAL",1)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		SetGlobal("AttackedThieves","GLOBAL",1)
END

IF
	Allegiance(Myself,ENEMY)
	Global("AttackedThieves","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("AttackedThieves","GLOBAL",1)
END

IF
	Die()
THEN
	RESPONSE #100
		SetGlobal("AttackedThieves","GLOBAL",1)
END


