BEGIN ~SOLA~

IF ~~ THEN BEGIN 0
  SAY ~Love him, Sime... His bite is deadly and sweet as almonds. Nothing is more tender than death...~
  IF ~~ THEN EXTERN ~SOLAUF~ 0
END

IF ~~ THEN BEGIN 1
  SAY ~Following each other 'til the last warmth came,
From our two hearts, two vast torches will pour
The reflection of their double flames
On our two spirits, these twin mirrors.~
  IF ~~ THEN EXTERN ~SOL~ 1
END