EXTEND_BOTTOM DOGHMA 0
  IF ~Global("RevealUmar","GLOBAL",1) OR(4) PartyHasItem("misc7L") PartyHasItem("miscbsim") PartyHasItem("miscbkel") PartyHasItem("miscblei")~ THEN REPLY ~A friend is afflicted by vampirism.  An old book suggested that followers of Oghma might know something about that.~ EXTERN DOGHMA 10
END

EXTEND_BOTTOM DOGHMA 3
  IF ~Global("RevealUmar","GLOBAL",1) OR(4) PartyHasItem("misc7L") PartyHasItem("miscbsim") PartyHasItem("miscbkel") PartyHasItem("miscblei")~ THEN REPLY ~A friend is afflicted by vampirism.  An old book suggested that followers of Oghma might know something about that.~ EXTERN DOGHMA 10
END

EXTEND_BOTTOM DOGHMA 7
  IF ~Global("RevealUmar","GLOBAL",1) OR(4) PartyHasItem("misc7L") PartyHasItem("miscbsim") PartyHasItem("miscbkel") PartyHasItem("miscblei")~ THEN REPLY ~A friend is afflicted by vampirism.  An old book suggested that followers of Oghma might know something about that.~ EXTERN DOGHMA 10
END

EXTEND_BOTTOM DOGHMA 9
  IF ~Global("RevealUmar","GLOBAL",1) OR(4) PartyHasItem("misc7L") PartyHasItem("miscbsim") PartyHasItem("miscbkel") PartyHasItem("miscblei")~ THEN REPLY ~A friend is afflicted by vampirism.  An old book suggested that followers of Oghma might know something about that.~ EXTERN DOGHMA 10
END