APPEND ~BAERIE25~

IF ~~ THEN BEGIN TS166
  SAY ~I thought... or never mind... You will laugh...~
  IF ~~ THEN EXTERN ~BVALYG25~ TS190
END

IF ~~ THEN BEGIN TS167
  SAY ~But you... you will laugh at me...~
  IF ~~ THEN EXTERN ~BVALYG25~ TS191
END

IF ~~ THEN BEGIN TS168
  SAY ~I thought that you... you might be Shaundakul's avatar... You are tall and handsome and dark-haired... You are dressed in the plain leather and you step lightly.~
  IF ~~ THEN EXTERN ~BVALYG25~ TS192
END

IF ~~ THEN BEGIN TS169
  SAY ~I knew... I knew you would laugh.~
  IF ~~ THEN EXTERN ~BVALYG25~ TS193
END

IF ~~ THEN BEGIN TS170
  SAY ~Valygar, do you ever think about anybody but <CHARNAME>?~
  IF ~~ THEN EXTERN ~BVALYG25~ TS194
END

IF ~~ THEN BEGIN TS171
  SAY ~No... nothing... Do not mind me...~
  IF ~~ THEN EXTERN ~BVALYG25~ TS195
END
END