APPEND ~BNALIA25~

IF ~~ THEN BEGIN TS59
  SAY ~Is not it ironic that the safest place for us is the Nine Hells itself?~
  IF ~~ THEN EXTERN ~BVALYG25~ TS202
END

IF ~~ THEN BEGIN TS60
  SAY ~And I thought it was bad enough to inherit the grim Castle as my Keep! I shudder when I think that <CHARNAME> might have to live in this place permanently if she... you know... ascends.~
  IF ~~ THEN EXTERN ~BVALYG25~ TS203
END

IF ~~ THEN BEGIN TS61
  SAY ~Well, it might be redone, I guess. Couple of bright color spots, may be a painting or two to decorate those gray walls? Large Shou Lung vases on the floor would do nicely to chase the shadows from the corners. Also she might want to trim Cespenar a bit...~
  IF ~~ THEN EXTERN ~BVALYG25~ TS204
END

IF ~~ THEN BEGIN TS62
  SAY ~It does sound odd, but I will find the place a bit friendlier and less frightening if something like that was done. I know, it is still the Nine Hells part and its grim nature will not change.~
  IF ~~ THEN EXIT
END

END